# encoding: utf-8
import os

path = r'c:\Users\shiqian\Peak\Patches\Act4MapPatch.cs'

code = 'using System.Collections.Generic;\n'
code += 'using System.Linq;\n'
code += 'using System.Reflection;\n'
code += 'using Godot;\n'
code += 'using HarmonyLib;\n'
code += 'using MegaCrit.Sts2.Core.Map;\n'
code += 'using MegaCrit.Sts2.Core.Models;\n'
code += 'using MegaCrit.Sts2.Core.Nodes.Screens.Map;\n'
code += 'using MegaCrit.Sts2.Core.Random;\n'
code += 'using MegaCrit.Sts2.Core.Runs;\n'
code += 'using peak.Core.Models.Acts;\n'
code += '\n'
code += 'namespace peak.Patches;\n'
code += '\n'
code += '[HarmonyPatch]\n'
code += 'public static class Act4MapPatch\n'
code += '{\n'
code += '    [HarmonyTargetMethod]\n'
code += '    static MethodBase TargetMethod()\n'
code += '    {\n'
code += '        return AccessTools.Constructor(typeof(StandardActMap), new[]\n'
code += '        {\n'
code += '            typeof(Rng), typeof(ActModel), typeof(bool),\n'
code += '            typeof(bool), typeof(bool),\n'
code += '            typeof(MapPointTypeCounts), typeof(bool),\n'
code += '        });\n'
code += '    }\n'
code += '\n'
code += '    [HarmonyPostfix]\n'
code += '    static void Postfix(StandardActMap __instance, ActModel actModel)\n'
code += '    {\n'
code += '        if (actModel is Act4)\n'
code += '            __instance.StartingMapPoint.PointType = MapPointType.Shop;\n'
code += '    }\n'
code += '}\n'
code += '\n'
code += '[HarmonyPatch]\n'
code += 'public static class Act4MapFixPatch\n'
code += '{\n'
code += '    private static List<MapCoord> _backupVisited = new();\n'
code += '\n'
code += '    [HarmonyPatch(typeof(NMapScreen), "SetMap")]\n'
code += '    [HarmonyPostfix]\n'
code += '    static void SetMap_Postfix(NMapScreen __instance, ActMap map)\n'
code += '    {\n'
code += '        var rsField = typeof(NMapScreen).GetField("_runState",\n'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\n'
code += '        if (rsField?.GetValue(__instance) is not IRunState runState || runState.Act is not Act4)\n'
code += '            return;\n'
code += '\n'
code += '        var bpnField = typeof(NMapScreen).GetField("_bossPointNode",\n'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\n'
code += '        if (bpnField?.GetValue(__instance) is not NMapPoint bossNode)\n'
code += '            return;\n'
code += '\n'
code += '        var distXField = typeof(NMapScreen).GetField("_distX",\n'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\n'
code += '        var distYField = typeof(NMapScreen).GetField("_distY",\n'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\n'
code += '        if (distXField == null || distYField == null) return;\n'
code += '\n'
code += '        float distX = (float)distXField.GetValue(__instance);\b'
code += '        float distY = (float)distYField.GetValue(__instance);\b'
code += '        int lastRow = map.GetRowCount() - ;\'
code += '        int bossCol = map.BossMapPoint.coord.col;\'
code += '\n'
code += '        float newBX = -500f + (float)bossCol * distX;\'
code += '        float lastGridRowY = (float)lastRow * (-dsty + 740;\'
code += '        float newBY = lastGridRowY + distY * 0.f;\'
code += '\n'
code += '        bossNode.Position = new Vector2(newBX, newBY);\'
code += '        GD.Print($"[Act4Fix] Boss pos=({newBX},{newBY}) lastRow={lastRow}");\'
code += '    }\'
code += ''
code += '    [HarmonyPatch(typeof(NMapScreen), "Open")]\'
code += '    [HarmonyPrefix]\'
code += '    static void Open_Prefix(NMapScreen __instance)\'
code += '    {\'
code += '        var rsField = typeof(NMapScreen).GetField("_runState",\'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '        if (rsField?.GetValue(__instance) is not RunState runState || runState.Act is not Act4)\'
code += '            return;\'
code += '\n'
code += '        var visitedField = typeof(RunState).GetField("_visitedMapCoords",\'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '        if (visitedField?.GetValue(runState) is not List<MapCoord> list)\'
code += '            return;\'
code += '\n'
code += '        if (list.Count > 0)\'
code += '        {'
code += '            _backupVisited = new List<MapCoord>(list);\'
code += '        }\'
code += '        else if (_backupVisited.Count > 0)\'
code += '        {'
code += '            list.Clear();\'
code += '            list.AddRange(_backupVisited);\'
code += '            GD.Print($"[Act4Fix] Restored {_backupVisited.Count} visited coords");\'
code += '        }\'
code += '    }'
code += '\n'
code += '    [HarmonyPostfix]\'
code += '    static void Open_Postfix(NMapScreen __instance)\'
code += '    {'
code += '        var rsField = typeof(NMapScreen).GetField("_ruState",\'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '        if (rsField?.GetValue(__instance) is not RunState runState || runState.Act is not Act4)\'
code += '            return;\'
code += '\b'
code += '        var hasPlayedField = typeof(NMapScreen).GetField("_hasPlayedAniation",\'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '        hasPlayedField?.SetValue(__instance, true);\'
code += '\n'
code += '        int lastRow = 0;\'
code += '        if (runState.VisitedMapCoords.Any())\'
code += '            lastRow = runState.VisitedMapCoords.Last().row;\'
code += '\n'
code += '        var dragField = typeof(NMapScreen).GetField("_targetDragPos",\'
code += '            BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '        var dragPos = dragField?.GetValue(__instance) is Vector2 dv ? dv : Vector2.Zero;\'
code += '\n'
code += '        float expectedY = -600f + (float)lastRow * 387.5f;\'
code += '        if (dragPos.Y < expectedY - 50f || dragPos.Y > expectedY + 50f)\'
code += '        {\'
code += '            var distYField = typeof(NMapScreen).GetField("_distY",\'
code += '                BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '            float distY = distYField != null ? (float)distYField.GetValue(__instance) : 387.5f;\'
code += '            float targetY = -600f + (float)lastRow * distY;\'
code += '            dragField?.SetValue(__instance, new Vector2(0f, targetY));\'
code += '\n'
code += '            var containerField = typeof(NMapScreen).GetField("_apContaner",\'
code += '                BindingFlags.Instance | BindingFlags.NonPublic);\'
code += '            if (containerField?.GetValue(__instance) is Control mc)\'
code += '            {\'
code += '                var p = mc.Position;\'
code += '                p.Y = targetY;\'
code += '                mc.Position = p;\'
code += '            }\'
code += '            GD.Print($"[Act4Fix] Camera fixed to row {lastRow} (y={targetY})");\'
code += '        }\'
code += '    }\'
code += '}\'

with open(path, 'w', encoding='utf8') as f:
    f.write(code)
print('Written OK')